### PR TITLE
update dependency on notifier-api

### PR DESCRIPTION
**Pull request by femkepetter**

### CODE REVIEW

**Comment by giacmir** [comment]
Hello @femkepetter, 
why is this needed? Composer should automatically resolve the latest 0.x dependency.

**Comment by femkepetter** [comment]
Hello @giacmir , this is needed because of the carot operator `^`, see: https://jubianchi.github.io/semver-check/#/

**Comment by giacmir** [comment]
Cool, I didn't know that caret has such limit for what it considers pre-release versions:

I'm reading [here](https://getcomposer.org/doc/articles/versions.md#caret-version-range-):

> For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0 and ^0.0.3 as >=0.0.3 <0.0.4.

In this case I'd rather put a generic `^0` as version constraint since we are not planning to release breaking changes before 1.0 and we are treating the first 0 as a major version.

https://jubianchi.github.io/semver-check/#/^0/0.2.0

**Comment by femkepetter** [comment]
Yes, `^0` seems better in this case!

**Pull request closed without merging**
